export default function Projects() {
  return (
    <div className="container">

      <div className="project">
        <div className="projectLeft">
          <strong>AI Lesion Identification</strong>
          <p className="projectRole">Team Lead</p>
          <p className="projectTech">Python, PyTorch, OpenCV</p>
        </div>

        <div className="projectRight">
          <p>
            Senior design project developing a medical image classification system
            for skin lesion identification, guided by the full engineering design
            process.
          </p>
          <ul>
            <li>Defined system requirements and constraints</li>
            <li>Led design reviews and validation planning</li>
            <li>Ensured traceability across the design lifecycle</li>
          </ul>
        </div>
      </div>

      <div className="project">
        <div className="projectLeft">
          <strong>Vehicle Energy Cost Model Comparison</strong>
          <p className="projectRole">Data Analysis & Modeling</p>
          <p className="projectTech">
            Python, Pandas, RouteE, OSMnx
          </p>
        </div>

        <div className="projectRight">
          <p>
            Compared trip-level fuel and energy cost estimates generated by RouteE
            against traditional MPG-based models to quantify differences under
            consistent fuel price assumptions.
          </p>
          <ul>
            <li>Computed per-trip energy and cost estimates across multiple vehicles</li>
            <li>Implemented city, highway, and combined MPG cost calculations</li>
            <li>Analyzed sensitivity to elevation and routing assumptions</li>
          </ul>
        </div>
      </div>

    </div>
  );
}
